export const allIcons = {
    '01d': '/src/assets/images/clear.png',
    '01n': 'https://openweathermap.org/img/wn/01n@2x.png',
    '02d': '/src/assets/images/cloud.png',
    '02n': 'https://openweathermap.org/img/wn/02n@2x.png',
    '03d': 'https://openweathermap.org/img/wn/03d@2x.png',
    '03n': 'https://openweathermap.org/img/wn/03n@2x.png',
    '04d': 'https://openweathermap.org/img/wn/04d@2x.png',
    '04n': 'https://openweathermap.org/img/wn/04n@2x.png',
    '09d': '/src/assets/images/rain.png',
    '09n': 'https://openweathermap.org/img/wn/09n@2x.png',
    '10d': 'https://openweathermap.org/img/wn/10d@2x.png',
    '10n': 'https://openweathermap.org/img/wn/10n@2x.png',
    '11d': 'https://openweathermap.org/img/wn/10d@2x.png',
    '11n': 'https://openweathermap.org/img/wn/11n@2x.png',
    '13d': '/src/assets/images/snow.png',
    '13n': '/src/assets/images/snow.png',
    '50d': '/src/assets/images/humidity.png',
    '50n': '/src/assets/images/humidity.png'
}